### PR TITLE
chore: update com.sleepycat.je dependency to version 18.3.12

### PR DESCRIPTION
**Pull request by rcristian**
version 5.0.84 is no longer available, the project does not compile.

### CODE REVIEW

**Review by tony-forgeai — APPROVED** [review]
It seems able to compile from my side, but not sure if its run behavior.

Once you're merged into the main branch, Please let me know because I have to update the link from the forgeai repo to reflect the changes.

**Comment by kronion** [comment]
@tony-forgeai I had this same issue:
```
Could not find artifact com.sleepycat:je:jar:5.0.84 in central (https://repo1.maven.org/maven2/)
```
I don't yet know if there's any risk updating this dependency, vs just installing from a different repository: https://mvnrepository.com/artifact/com.sleepycat/je/5.0.84

Are there tests we can run to determine if this change is safe?

**Comment by tony-forgeai** [comment]
@kronion it is a bit surprised that you're still encounter the issue for version 5.0.84.
The PR is merged last Dec, and should download version 18.3.12 instead.
Can you double check the POM.xml file and make sure it is the correct one like [this](https://github.com/forgeAI/crawler4j/blob/development/pom.xml) ?
@rcristian , do you encounter the same issue?

**Comment by kronion** [comment]
I think the issue is that the submodules specify older (outdated?) branches. https://github.com/forgeAI/forgeai/blob/development/.gitmodules

I wasn't able to compile until I changed both `forgeai-schema` and `crawler4j` to use the `development` branch instead of `forgeai_java11`.

**Pull request merged**
